### ISSUE TITLE
(Query) Version compatability?

### ISSUE THREAD

**Issue by pcass-epcc** [sileht/cmk_fastchecker#1]
This is a really cool project - I'm in the unfortunate position of maintaining a monitoring service where we don't currently have the ability to use the micro core.  One of our issues is we have 15 (and could monitor 38) hosts with > 1000 services (826 multipath services each) so cutting down on the forking will help in the short term

Is this compatible with 1.2.8 and with 1.5.0?  I'm on the former and want to move to the latter when possible

**Comment by sileht** [comment]
I don't really offer support on this, and check_mk entreprise does exactly the same thing with less hack.
That's said, I use it with 1.4.0 currently and not yet upgrade to 1.5.0, but I don't see why it wouldn't work.

**Comment by pcass-epcc** [comment]
Thanks - I assumed no support, just wanted to check there wasn't an obvious reason it wouldn't work.  If I do run into problems (and solve them) I will of course make a PR :)
